"""TradingView Pine v6 exporter for the ORB family.

Generates a self-contained Pine v6 *strategy* from an ORBConfig: runs in TV's
backtester and fires long/short/flat alerts for live testing.

IMPORTANT: this is a LIVE-TESTING COMPANION, not a re-validation of our engine.
TradingView's bar model, session handling, and fill assumptions differ from
karmabase, so results will not match exactly. Treat divergences as expected.
"""
from __future__ import annotations

from datetime import time, timedelta, datetime

from .config import ORBConfig


def _or_session(cfg: ORBConfig) -> str:
    o = cfg.session_open
    end_min = o.hour * 60 + o.minute + cfg.or_minutes
    e = time(end_min // 60, end_min % 60)
    return f"{o:%H%M}-{e:%H%M}"


def _hhmm(t: time) -> str:
    return f"{t:%H%M}"


def to_pine(cfg: ORBConfig, name: str | None = None) -> str:
    name = name or f"KarmaBase ORB [{cfg.variant}] {cfg.instrument}"
    tz = "America/New_York"
    or_sess = _or_session(cfg)
    eod = _hhmm(cfg.eod_flat)
    cutoff = _hhmm(cfg.entry_cutoff)
    # resolve commission like the engine (None => instrument default)
    commission = cfg.commission if cfg.commission is not None \
        else cfg.instrument_spec().commission

    # per-variant entry filter (VWAP gate) and entry style
    vwap_long = "close > vwapv" if cfg.use_vwap else "true"
    vwap_short = "close < vwapv" if cfg.use_vwap else "true"
    retest = cfg.variant == "retest"

    # stop expression by mode
    if cfg.stop_mode == "range_mid":
        long_stop, short_stop = "orMid", "orMid"
    elif cfg.stop_mode == "atr":
        long_stop = f"close - {cfg.atr_mult} * atrv"
        short_stop = f"close + {cfg.atr_mult} * atrv"
    elif cfg.stop_mode == "fixed_ticks":
        d = cfg.stop_ticks * cfg.instrument_spec().tick_size
        long_stop, short_stop = f"close - {d}", f"close + {d}"
    else:  # opposite_range
        long_stop, short_stop = "orLow", "orHigh"

    # target by exit mode
    if cfg.exit_mode == "measured_move":
        long_tgt, short_tgt = "entryP + orRange", "entryP - orRange"
    else:  # r_multiple (trail handled by TV trailing not modeled here)
        long_tgt = f"entryP + {cfg.target_R} * longR"
        short_tgt = f"entryP - {cfg.target_R} * shortR"

    entry_block = _retest_entry() if retest else _breakout_entry()

    return f'''//@version=6
// Auto-generated by KarmaBase (karmabase/pine.py) from strategies/orb.md
// Variant: {cfg.variant} | Instrument: {cfg.instrument} | OR: {cfg.or_minutes}m
// NOTE: live-testing companion. TV fills/sessions differ from the karmabase engine;
// results will not match the backtest exactly.
strategy("{name}", overlay=true, calc_on_every_tick=false,
     default_qty_type=strategy.percent_of_equity, default_qty_value=100,
     initial_capital={int(cfg.starting_capital)}, commission_type=strategy.commission.cash_per_order,
     commission_value={commission}, slippage={cfg.slippage_ticks})

// ---- inputs (defaults mirror the tested config) ----
orSess   = input.session("{or_sess}", "Opening-range window")
tz       = input.string("{tz}", "Session timezone")
targetR  = input.float({cfg.target_R}, "Target (R multiple)", step=0.5)
riskPct  = input.float({cfg.risk_pct*100}, "Risk per trade (%)", step=0.25) / 100.0
useTimeStop = input.bool({str(cfg.use_time_stop).lower()}, "Time-stop failed breakouts")
timeStopBars = input.int({cfg.time_stop_bars}, "Time-stop bars")

vwapv = ta.vwap(hlc3)
atrv  = ta.atr({cfg.atr_len})

// ---- opening range (resets each session) ----
inOR   = not na(time(timeframe.period, orSess, tz))
newDay = ta.change(time("D")) != 0
var float orHigh = na
var float orLow  = na
if newDay
    orHigh := na
    orLow  := na
if inOR
    orHigh := na(orHigh) ? high : math.max(orHigh, high)
    orLow  := na(orLow)  ? low  : math.min(orLow, low)
orReady = (not inOR) and (not na(orHigh))
orMid   = na(orHigh) ? na : (orHigh + orLow) / 2.0
orRange = na(orHigh) ? na : (orHigh - orLow)

// session gates
afterCutoff = not na(time(timeframe.period, "{cutoff}-{eod}", tz))
flatTime    = not na(time(timeframe.period, "{eod}-1600", tz))

// plot the range
plot(orReady ? orHigh : na, "OR High", color.new(color.teal, 0), 2, plot.style_linebr)
plot(orReady ? orLow  : na, "OR Low",  color.new(color.red, 0), 2, plot.style_linebr)

longFilter  = {vwap_long}
shortFilter = {vwap_short}

{entry_block}

// ---- risk / exits ----
entryP = strategy.position_avg_price
longR  = math.abs(entryP - ({long_stop}))
shortR = math.abs(({short_stop}) - entryP)
if strategy.position_size > 0
    strategy.exit("L-exit", from_entry="Long", stop={long_stop}, limit={long_tgt})
if strategy.position_size < 0
    strategy.exit("S-exit", from_entry="Short", stop={short_stop}, limit={short_tgt})

// time-stop: re-enters the range without follow-through
barsHeld = ta.barssince(strategy.position_size[1] == 0 and strategy.position_size != 0)
if useTimeStop and strategy.position_size != 0 and barsHeld <= timeStopBars
    reenter = strategy.position_size > 0 ? close < orHigh : close > orLow
    if reenter
        strategy.close_all(comment="time-stop")

// EOD flat
if flatTime
    strategy.close_all(comment="eod")

// ---- alerts ----
alertcondition(strategy.position_size > 0 and strategy.position_size[1] <= 0, "ORB Long", "KarmaBase ORB: LONG")
alertcondition(strategy.position_size < 0 and strategy.position_size[1] >= 0, "ORB Short", "KarmaBase ORB: SHORT")
alertcondition(strategy.position_size == 0 and strategy.position_size[1] != 0, "ORB Flat", "KarmaBase ORB: FLAT")
'''


def _breakout_entry() -> str:
    return '''// classic / vwap: enter on a close beyond the range
canEnter = orReady and not afterCutoff
if canEnter and close > orHigh and longFilter
    strategy.entry("Long", strategy.long)
if canEnter and close < orLow and shortFilter
    strategy.entry("Short", strategy.short)'''


def _retest_entry() -> str:
    return '''// retest: after a breakout, enter on a pullback (limit) to the broken level
var bool armedLong  = false
var bool armedShort = false
if newDay
    armedLong  := false
    armedShort := false
if orReady and close > orHigh
    armedLong := true
if orReady and close < orLow
    armedShort := true
canEnter = orReady and not afterCutoff
if canEnter and armedLong and longFilter
    strategy.entry("Long", strategy.long, limit=orHigh)
    armedLong := false
if canEnter and armedShort and shortFilter
    strategy.entry("Short", strategy.short, limit=orLow)
    armedShort := false'''
